### ISSUE TITLE
Strange behavior using Dev Spaces with Asp.Net Core

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#114]
When my services are trying to contact a new service (a service that I have started using F5 in VS) they fail with the following error:

`System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestM
`

In azure it looks like this:
![image](https://user-images.githubusercontent.com/12099277/59292894-3eddc500-8c7e-11e9-8f9d-001344a5618f.png)

![image](https://user-images.githubusercontent.com/12099277/59293045-a6941000-8c7e-11e9-871a-f0105b4bd2a3.png)

I also have "Running" versions of the services higher up the the list.

If I wait for a few hours, the rouge controllers/containers goes away and the calls seems to start working.

Any ideas on whats causes Dev Spaces to keep theese rouge controllers/containers?
Can theese block my calls to the running controllers/containers ?

**Comment by Eneuman** [comment]
Everything looks okey in the kubernetes portal so I guess this is some type of sync issue with the azure portal. 
Closing this for now.
