### ISSUE TITLE
Adding RabbitMQ support to .NET Core MicroService

### ISSUE THREAD

**Issue by xylotron** [Azure/dev-spaces#259]
**Describe the bug**
RabbitMQ Client:  None of the specified endpoints were reachable.
 
**To Reproduce**
I have created a nuget.config file with proper package references for RabbitMQ. The project runs fine on localhost. So no problem with the references, but I don't know how to add image of RabbitMQ on DevSpaces. I have the following Docker File which I use to run through  'azds up'.
The project runs fine on my local machine. Do I need to add docker-compose.yml? If so how do I add rabbitmq support. I am very new to this, can someone please guide me through this?
```
FROM microsoft/dotnet:2.2-aspnetcore-runtime-nanoserver-1803 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk-nanoserver-1803 AS build
WORKDIR /src
COPY ["src/Customer.WebApi/Customer.WebApi.csproj", "src/Customer.WebApi/"]
COPY ["src/Customer.WebApi/nuget.config", "src/Customer.WebApi/"]
RUN dotnet restore "src/Customer.WebApi/Customer.WebApi.csproj"
COPY . .
WORKDIR "/src/src/Customer.WebApi"
RUN dotnet build "Customer.WebApi.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "Customer.WebApi.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Customer.WebApi.dll"]
```
 
**Expected behavior**
RabbitMQ creates Queue and wait for Message Publishing
 
**Logs**
```
2019-12-20T11:50:55.8838485Z | SDK | WARNG | Streaming pod events canceled
2019-12-20T11:50:56.1160622Z | SDK | TRACE | Dependency: Kubernetes <json>{"target":"ListPodsInNamespaceAsync","success":true,"duration":null,"properties":{"targetCluster":"UserCluster"}}</json>
2019-12-20T11:50:56.1220868Z | SDK | TRACE | GetServicePortForwardInfoAsync: get 3 pods.
2019-12-20T11:50:58.2366785Z | SDK | TRACE | Service 'customerwebapi' port 80 (http) is available via port forwarding at http://localhost:53282
2019-12-20T11:50:58.2448850Z | SDK | TRACE | press Ctrl+C to detach
2019-12-20T11:50:58.8639862Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:55 INF] Configuring web host (Customer.WebApi)...
2019-12-20T11:50:58.8657053Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:56 INF] Applying migrations (Customer.WebApi)...
2019-12-20T11:50:58.8697345Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:56 INF] Starting web host (Customer.WebApi)...
2019-12-20T11:50:58.8703660Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:56 WRN] No XML encryptor configured. Key {a13ce5bf-568c-4ae3-bdc9-e71b81d1fbb0} may be persisted to storage in unencrypted form.
2019-12-20T11:50:58.8709558Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:57 INF] RabbitMQ Client is trying to connect
2019-12-20T11:50:58.8758043Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:57 WRN] RabbitMQ Client could not connect after 2.0s (None of the specified endpoints were reachable)
2019-12-20T11:50:58.8771792Z | SDK | TRACE | customerwebapi-79c8694949-642h2: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: Unable to write data to the transport connection: Broken pipe. ---> System.Net.Sockets.SocketException: Broken pipe
2019-12-20T11:50:58.8778142Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2019-12-20T11:50:58.8784409Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    --- End of inner exception stack trace ---
2019-12-20T11:50:58.8790862Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2019-12-20T11:50:58.9409321Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.IO.BufferedStream.Flush()
2019-12-20T11:50:58.9430737Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Impl.SocketFrameHandler.SendHeader()
2019-12-20T11:50:58.9470067Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
2019-12-20T11:50:58.9476654Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
2019-12-20T11:50:58.9482594Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
2019-12-20T11:50:58.9489933Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:50:58.9497272Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    --- End of inner exception stack trace ---
2019-12-20T11:50:58.9503034Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:50:58.9512316Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at .BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection.<TryConnect>b__11_2()
2019-12-20T11:50:58.9568603Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Policy.<>c__DisplayClass144_0.<Execute>b__0(Context ctx, CancellationToken ct)
2019-12-20T11:50:58.9573637Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
2019-12-20T11:50:58.9585489Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2019-12-20T11:50:59.7091250Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:50:59 WRN] RabbitMQ Client could not connect after 4.0s (None of the specified endpoints were reachable)
2019-12-20T11:50:59.7221534Z | SDK | TRACE | customerwebapi-79c8694949-642h2: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: Unable to write data to the transport connection: Cannot access a disposed object.
2019-12-20T11:50:59.7245318Z | SDK | TRACE | customerwebapi-79c8694949-642h2: Object name: 'System.Net.Sockets.Socket'.. ---> System.ObjectDisposedException: Cannot access a disposed object.
2019-12-20T11:50:59.7259751Z | SDK | TRACE | customerwebapi-79c8694949-642h2: Object name: 'System.Net.Sockets.Socket'.
2019-12-20T11:50:59.7273760Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode)
2019-12-20T11:50:59.7284143Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2019-12-20T11:50:59.7293875Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    --- End of inner exception stack trace ---
2019-12-20T11:50:59.7304889Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
2019-12-20T11:50:59.7319083Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at System.IO.BufferedStream.Flush()
2019-12-20T11:50:59.7325508Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Impl.SocketFrameHandler.SendHeader()
2019-12-20T11:50:59.7968616Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
2019-12-20T11:50:59.7984651Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
2019-12-20T11:50:59.8025267Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
2019-12-20T11:50:59.8031963Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:50:59.8040000Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    --- End of inner exception stack trace ---
2019-12-20T11:50:59.8047109Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:50:59.8054308Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at .BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection.<TryConnect>b__11_2()
2019-12-20T11:50:59.8061515Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Policy.<>c__DisplayClass144_0.<Execute>b__0(Context ctx, CancellationToken ct)
2019-12-20T11:50:59.8068763Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
2019-12-20T11:50:59.8082837Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2019-12-20T11:51:03.7273796Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:51:03 WRN] RabbitMQ Client could not connect after 8.0s (None of the specified endpoints were reachable)
2019-12-20T11:51:03.7302845Z | SDK | TRACE | customerwebapi-79c8694949-642h2: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: connection.start was never received, likely due to a network timeout
2019-12-20T11:51:03.7308491Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
2019-12-20T11:51:03.7315027Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
2019-12-20T11:51:03.7320679Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
2019-12-20T11:51:03.7325435Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:51:03.7330387Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    --- End of inner exception stack trace ---
2019-12-20T11:51:03.7337974Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:51:03.7351023Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at .BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection.<TryConnect>b__11_2()
2019-12-20T11:51:03.7354969Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Policy.<>c__DisplayClass144_0.<Execute>b__0(Context ctx, CancellationToken ct)
2019-12-20T11:51:03.8109468Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
2019-12-20T11:51:03.8115492Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2019-12-20T11:51:11.7375975Z | SDK | TRACE | customerwebapi-79c8694949-642h2: [11:51:11 WRN] RabbitMQ Client could not connect after 16.0s (None of the specified endpoints were reachable)
2019-12-20T11:51:11.7380898Z | SDK | TRACE | customerwebapi-79c8694949-642h2: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> System.IO.IOException: connection.start was never received, likely due to a network timeout
2019-12-20T11:51:11.7391868Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.StartAndTune()
2019-12-20T11:51:11.7393972Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.Connection.Open(Boolean insist)
2019-12-20T11:51:11.7395749Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.Framing.Impl.AutorecoveringConnection.Init(IFrameHandler fh)
2019-12-20T11:51:11.7397402Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:51:11.7399511Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    --- End of inner exception stack trace ---
2019-12-20T11:51:11.7401176Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
2019-12-20T11:51:11.7403179Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at .BuildingBlocks.EventBusRabbitMQ.DefaultRabbitMQPersistentConnection.<TryConnect>b__11_2()
2019-12-20T11:51:11.8211541Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Policy.<>c__DisplayClass144_0.<Execute>b__0(Context ctx, CancellationToken ct)
2019-12-20T11:51:11.8225392Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.RetrySyntax.<>c__DisplayClass12_1.<WaitAndRetry>b__1(Context ctx, CancellationToken ct)
2019-12-20T11:51:11.8232968Z | SDK | TRACE | customerwebapi-79c8694949-642h2:    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, IEnumerable`1 shouldRetryExceptionPredicates, IEnumerable`1 shouldRetryResultPredicates, Func`1 policyStateFactory)
2019-12-20T11:51:25.0152399Z | SDK | WARNG | Channel exception on read operation for service log
```
 
**Environment Details**
Client used (CLI):
Azure Dev Spaces CLI
1.0.20191204.4
API v3.2
Client's version:
Operating System: Windows 10

**Comment by lolodi** [comment]
Hello!
Thanks for contacting us.
From your logs it looks like the RabbitMQ library was loaded correctly, and everything build successfully. The problem seems to happen when the client tries to connect to the instance of RabbitMQ and it doesn't find it. Where is your RabbitMQ running? Locally or in the cluster? Is your connection string set properly to connect it from the cluster?

**Comment by xylotron** [comment]
I have rabbitmq deployed in the same namespace as the microservice devspace deployment.

Rabbitmq InternalEndpoint (as seen on Kubernetes Dashboard):
`rabbitmq.devspace-dev:15672 TCP`

I used the following command to deploy rabbitmq to kubernetes:
`kubectl --namespace=devspace-dev create -f rabbitmq.yml`

with the following rabbitmq.yml:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:management
    name: rabbitmq
    ports:
    - containerPort: 15672
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

Following is the configuration in my .NET Core WebApi's appsettings.json:

```
"AzureServiceBusEnabled": false,
  "SubscriptionClientName": "Invoicing",
  "CheckUpdateTime": "30000",
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "EventBusRetryCount": 5,
  "OrderClientName": "Invoicing",
  "EventBusConnection": "rabbitmqdevspace-dev",
  "EventBusUserName": "guest",
  "EventBusPassword": "guest",
  "UseVault": false,
  "Vault": {
    "Name": "eshop",
    "ClientId": "your-clien-id",
    "ClientSecret": "your-client-secret"
  }
```
And the following in my startup.cs:

```
public static IServiceCollection AddCustomIntegrations(this IServiceCollection services, IConfiguration configuration)
        {
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();

            services.AddTransient<ICustomerIntegrationEventService, CustomerIntegrationEventService>();

            if (configuration.GetValue<bool>("AzureServiceBusEnabled"))
            {
                services.AddSingleton<IServiceBusPersisterConnection>(sp =>
                {
                    var logger = sp.GetRequiredService<ILogger<DefaultServiceBusPersisterConnection>>();

                    var serviceBusConnectionString = configuration["EventBusConnection"];
                    var serviceBusConnection = new ServiceBusConnectionStringBuilder(serviceBusConnectionString);

                    return new DefaultServiceBusPersisterConnection(serviceBusConnection, logger);
                });
            }
            else
            {
                services.AddSingleton<IRabbitMQPersistentConnection>(sp =>
                {
                    var logger = sp.GetRequiredService<ILogger<DefaultRabbitMQPersistentConnection>>();


                    var factory = new ConnectionFactory()
                    {
                        HostName = configuration["EventBusConnection"],
                        DispatchConsumersAsync = true,
                        RequestedHeartbeat = 60,
                        Ssl =
                            {
                                ServerName = configuration["EventBusConnection"],
                                Enabled = true
                            }
                    };

                    if (!string.IsNullOrEmpty(configuration["EventBusUserName"]))
                    {
                        factory.UserName = configuration["EventBusUserName"];
                    }

                    if (!string.IsNullOrEmpty(configuration["EventBusPassword"]))
                    {
                        factory.Password = configuration["EventBusPassword"];
                    }

                    var retryCount = 5;
                    if (!string.IsNullOrEmpty(configuration["EventBusRetryCount"]))
                    {
                        retryCount = int.Parse(configuration["EventBusRetryCount"]);
                    }

                    return new DefaultRabbitMQPersistentConnection(factory, logger, retryCount);
                });
            }


            return services;
        }

```

Is this all correct or there is something missing or it is completely wrong?
