### ISSUE TITLE
Pod not listening on port after being moved to another node

### ISSUE THREAD

**Issue by Eneuman** [Azure/dev-spaces#261]
**Describe the bug**
I am using Dev Spaces on a K8 cluster with 2 nodes.

I have 2 micro services. Service "A" is deployed to Node 1 and Service "B" is deployed to node 2.
Both services are deployed using VS F5 (Debug)
Service A is calling Service B using REST and everything is working fine.

Now node 2 gets updated and rebooted by MS so K8 moves Service "B" to node 1.
Now Service "B" stops listening for calls and any call from Service "A" failes with the following error message:

```
System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
```

If I deploy Service "B" again, using F5 (Debug) everything starts to work.

The image below shows the pod running, but it does not accept any calls made to it:
![image](https://user-images.githubusercontent.com/12099277/71447625-017be900-2731-11ea-9178-9d12ef8694ea.png)

**Comment by sanar-microsoft** [comment]
@Eneuman Thanks for pointing out this issue, just to be sure that there is no network problem on the cluster can you try recreating(delete) the pods in kube-system and azds namespace, especially traefik, coredns and kube-proxy pods. Also to rule out any issue with the Dockerfile.develop, do you see the same behavior when you do `azds up` through the CLI?

I've run into a similar issue before due to a network issue on the cluster and after restarting pods in kube-system namespace and doing `azds down` before running F5 again fixed the issue.

**Comment by Eneuman** [comment]
Hi,
I tried your suggestions but it didn't help :(
The entrypoint.sh is not being run.

Here are some info about the service I just tried this with (after it was recreated)
![image](https://user-images.githubusercontent.com/12099277/71522160-da095580-28c3-11ea-9c60-fe31a6990890.png)

![image](https://user-images.githubusercontent.com/12099277/71522180-eee5e900-28c3-11ea-8f2d-fffe255b8dad.png)

**Comment by sanar-microsoft** [comment]
@Eneuman  Were you able to try `azds down` and `azds up` on the service? Are you able to hit the endpoint then? 
If you do F5 again on this pod, do things work or do you still get Bad Gateway?

During F5 scenario the application is started by another process after receiving a request from the client(VS), my guess is that the call never reached the running process in the pod and the actual application is therefore not running.  I'm investigating further.

**Comment by Eneuman** [comment]
Hi
Yeah, after pressing F5 the app starts. But if I delete the pod, it does not start the app and I receive a bad gateway error.

All our pods are created using F5 because of our development model. But since we are using 2 nodes in our cluster, the master nodes moves our services around automatically and this makes them stop working. Since we have 36 micro services, we need to manually start the moved services each day :(.

Is it possible to make a pod, started by F5, to also start the app when it gets recreated by the scheduler?

**Comment by sanar-microsoft** [comment]
Our current implementation doesn't support it, but I've opened a work item on the team to address it. 
For services that don't require debugging, running them through `azds up` instead of F5 can keep the pods running even if they are moved between the nodes.
