### ISSUE TITLE
No more able to debug with azure dev spaces

### ISSUE THREAD

**Issue by antogh** [Azure/dev-spaces#33]
I was able to debug an ASP.NET CORE web app deployed on AKS cluster the first time I enabled azure dev spaces

Now I want to debug again the same app and it doesn't work anymore. 

service and deployment are created on the cluster but the pod never gets created . Last time I tried I got this error in the azure dev spaces tab

Starting warmup for project 'WebApplication1'.
Using dev space 'default' with target 'TestAks'
Release "default-webapplication1-bf1cdcbc" does not exist. Installing it now.
NAME:   default-webapplication1-bf1cdcbc
LAST DEPLOYED: Thu Oct 25 18:35:09 2018
NAMESPACE: default
STATUS: DEPLOYED
RESOURCES:
==> v1/Service
NAME             TYPE       CLUSTER-IP   EXTERNAL-IP  PORT(S)  AGE
webapplication1  ClusterIP  10.0.195.68  <none>       80/TCP   1s
==> v1beta2/Deployment
NAME             DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
webapplication1  1        0        0           0          1s
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app=webapplication1,release=default-webapplication1-bf1cdcbc" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
Failed to build container image.
Service cannot be started.
An error occurred during warmup for project 'WebApplication1':
System.InvalidOperationException: Service cannot be started.
   at Microsoft.Mindaro.Client.ManagementClients.ServiceManagementClientImplementation.<ExecuteNextIterationAsync>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Mindaro.Client.ManagementClients.ServiceManagementClient.<ExecuteNextIterationAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Client.DevSpacesServiceClient.<>c__DisplayClass26_0.<<StartDebugAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Logging.PerfLoggerExtensions.<ExecuteOperationAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Client.DevSpacesServiceClient.<>c__DisplayClass26_0.<<StartDebugAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Logging.PerfLoggerExtensions.<ExecuteOperationAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.DebugService.<WarmupProjectAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.BackgroundWarmupService.<>c__DisplayClass9_0.<<ExecuteWarmupAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Logging.PerfLoggerExtensions.<ExecuteOperationAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.BackgroundWarmupService.<ExecuteWarmupAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.BackgroundWarmupService.<>c__DisplayClass7_0.<<WarmupProject>b__3>d.MoveNext()
Enabling debugging...

**Comment by lisaguthrie** [comment]
@antogh what region is your cluster/controller in? We're patching Dev Spaces controllers in East US and West US 2 right now, so you may experience some intermittent failures while that's happening. If you're **not** in one of those two regions, let me know so we can investigate further.

**Comment by antogh** [comment]
Hi @lisaguthrie  
the aks cluster is in west Europe (and me too) 
yesterday the dev space debugger  was working fine

now it seems that VS gets stuck when it tries to deploy the container to the cluster to create the pod . Vs is still able to create the service and the deployment in the cluster . The problem occurs creating the pod

**Comment by lisaguthrie** [comment]
@antogh I just heard from one of the devs that we are patching West Europe now, too :) Can you wait for a couple of hours and try again?

**Comment by antogh** [comment]
@lisaguthrie  now magically  it works again :) 
hope the next time I need it will still work.
Let’s wait another day and then close the issue ;)

**Comment by lisaguthrie** [comment]
@antogh glad to hear it :) And sorry for the inconvenience! Definitely let us know if you run into further issues.
