### ISSUE TITLE
Error debugging Kubernetes app in Visual Studio + Azure Dev Spaces

### ISSUE THREAD

**Issue by dpolist** [Azure/dev-spaces#343]
Whenever I start a debugging session in Visual Studio 2019 version 16.6.0 usinf Azure Deb Spaces in a freshly-created "WeatherForecast" app, I get the following error during the warmup of my project:

Starting warmup for project 'Kubernetes1'.
An error occurred during warmup for project 'Kubernetes1':
Autofac.Core.DependencyResolutionException: An exception was thrown while executing a resolve operation. See the InnerException for details. ---> Could not merge user cluster kubeconfig into kubeconfig file 'C:\Users\danielp\.kube\config'. (See inner exception for details.) ---> Microsoft.Azure.DevSpaces.Common.Exceptions.KubectlException: Could not merge user cluster kubeconfig into kubeconfig file 'C:\Users\danielp\.kube\config'. ---> Microsoft.Azure.DevSpaces.Common.Exceptions.KubectlMergeConfigException: An error occurred when merging config files. Please run 'KUBECONFIG=C:\Users\danielp\.azds\kubeconfig-temp:C:\Users\danielp\.kube\config kubectl config view --flatten' to manually merge the config files and try again.
   at Microsoft.Azure.DevSpaces.Common.Kubernetes.KubeConfigClient.<>c__DisplayClass12_0.<MergeIntoKubeConfigFile>b__1(String error)
   at Microsoft.Azure.DevSpaces.Common.Kubernetes.KubectlImpl.RunShortRunningCommand(String kubectlFilePath, KubernetesCommandName commandName, String command, Action`1 onStdOut, Action`1 onStdErr, CancellationToken cancellationToken, Dictionary`2 envVariables, Boolean log137ExitCodeErrorAsWarning)
   at Microsoft.Azure.DevSpaces.Common.Kubernetes.KubeConfigClient.RunKubectlCommand(KubernetesCommandName commandName, String command, CancellationToken cancellationToken, Action`1 onStdOut, Action`1 onStdErr, Dictionary`2 envVariables, Boolean shortRunningOperation, Boolean useKubectlFromPath)
   at Microsoft.Azure.DevSpaces.Common.Kubernetes.KubeConfigClient.MergeIntoKubeConfigFile(String kubeConfigContent, CancellationToken cancellationToken, Boolean useKubectlFromPath)
   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.EnsureKubectlConfigExists()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.EnsureKubectlConfigExists()
   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClientImplementation.InitializeAsync()
   at Autofac.AutofacRegistrationBuilderExtensions.<>c__DisplayClass0_1`3.<InitializeOnActivation>b__1()
   at Microsoft.Azure.DevSpaces.Common.Utilities.AsyncHelpers.<>c__DisplayClass0_0.<<RunSync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.DevSpaces.Common.Utilities.AsyncHelpers.ExclusiveSynchronizationContext.BeginMessageLoop()
   at Microsoft.Azure.DevSpaces.Common.Utilities.AsyncHelpers.RunSync(Func`1 task)
   at Autofac.AutofacRegistrationBuilderExtensions.<>c__DisplayClass0_0`3.<InitializeOnActivation>b__0(IActivatingEventArgs`1 e)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass30_0.<OnActivating>b__0(Object s, ActivatingEventArgs`1 e)
   at Autofac.Core.Registration.ComponentRegistration.RaiseActivating(IComponentContext context, IEnumerable`1 parameters, Object& instance)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.<Execute>b__5_0()
   at Autofac.Core.Lifetime.LifetimeScope.GetOrCreateAndShare(Guid id, Func`1 creator)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Features.LazyDependencies.LazyRegistrationSource.<>c__DisplayClass5_1`1.<CreateLazyRegistration>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.DevSpaces.Client.ManagementClients.ServiceManagementClient.StartIterationTracking(ServiceIterateOption iterateOption, Func`2 getTunnelPortHandler, Func`2 portStatusUpdateHandler, IProgress`1 progress, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Client.DevSpacesServiceClient.EnsureIterationTrackingStarted(ServiceIterateOption iterateOption, String projectFilePath, Nullable`1 serviceTunnelPort, IProgress`1 progress)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Client.DevSpacesServiceClient.<>c__DisplayClass27_0.<<StartDebugAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Logging.PerfLoggerExtensions.<ExecuteOperationAsync>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.DebugService.<WarmupProjectAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.BackgroundWarmupService.<>c__DisplayClass13_0.<<ExecuteWarmupAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Common.Logging.PerfLoggerExtensions.<ExecuteOperationAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.BackgroundWarmupService.<ExecuteWarmupAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Azure.DevSpaces.Tools.Package.Services.BackgroundWarmupService.<>c__DisplayClass10_0.<<WarmupProject>b__4>d.MoveNext()
Enabling debugging...

**Comment by dpolist** [comment]
My .kube/config file had several existing configurations (including other environments, such as EKS). I removed it and it worked fine :)
