### ISSUE TITLE
I get an error when installing Dev Spaces

### ISSUE THREAD

**Issue by mapoitras** [Azure/dev-spaces#43]
I have a fairly new AKS Cluster
C:\Users\mapoitra>az aks get-upgrades --name myAKS --resource-group MAPAKSDemoRG --output table
Name     ResourceGroup    MasterVersion    NodePoolVersion    Upgrades
-------  ---------------  ---------------  -----------------  ----------
default  MAPAKSDemoRG     1.11.3           1.11.3             1.11.4

I get an error installing Dev Spaces
C:\Users\mapoitra>az aks use-dev-spaces -g MAPAKSDemoRG -n MyAKS
The installed extension 'dev-spaces-preview' is in preview.
unsupported operand type(s) for |: 'DefaultStr' and 'bool'
Traceback (most recent call last):
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\knack\knack\cli.py", line 197, in invoke
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\azure-cli-core\azure\cli\core\commands\__init__.py", line 336, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\six\six.py", line 693, in reraise
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\azure-cli-core\azure\cli\core\commands\__init__.py", line 310, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\knack\knack\commands.py", line 109, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\azure-cli-core\azure\cli\core\__init__.py", line 420, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-972ovukd\azure-cli-acs\azure\cli\command_modules\acs\custom.py", line 1451, in aks_use_dev_spaces
  File "C:\Users\mapoitra\.azure\cliextensions\dev-spaces-preview\azext_dev_spaces_preview\custom.py", line 38, in ads_use_dev_spaces
    azds_cli = _install_dev_spaces_cli(update)
  File "C:\Users\mapoitra\.azure\cliextensions\dev-spaces-preview\azext_dev_spaces_preview\custom.py", line 118, in _install_dev_spaces_cli
    should_install_azds = force_install | (not _is_dev_spaces_installed(azds_cli))
TypeError: unsupported operand type(s) for |: 'DefaultStr' and 'bool'

**Comment by mapoitras** [comment]
I do have an older version.  2.0.34.  Sorry.  I should of thought of that.  Will upgrade and retry.

C:\Users\mapoitra>az --version
azure-cli (2.0.34)

acr (2.0.26)
acs (2.0.34)
advisor (0.5.1)
ams (0.1.1)
appservice (0.1.33)
backup (1.1.1)
batch (3.2.3)
batchai (0.2.3)
billing (0.1.8)
cdn (0.0.14)
cloud (2.0.13)
cognitiveservices (0.1.13)
command-modules-nspkg (2.0.1)
configure (2.0.15)
consumption (0.3.1)
container (0.1.24)
core (2.0.34)
cosmosdb (0.1.21)
dla (0.1.0)
dls (0.0.21)
dms (0.0.1)
eventgrid (0.1.12)
eventhubs (0.1.3)
extension (0.0.14)
feedback (2.1.1)
find (0.2.9)
interactive (0.3.21)
iot (0.1.21)
keyvault (2.0.22)
lab (0.0.22)
maps (0.1.0)
monitor (0.1.7)
network (2.1.3)
nspkg (3.0.2)
policyinsights (0.1.0)
profile (2.0.25)
rdbms (0.2.3)
redis (0.2.13)
reservations (0.1.2)
resource (2.0.30)
role (2.0.24)
servicebus (0.1.2)
servicefabric (0.0.12)
sql (2.0.27)
storage (2.0.34)
vm (2.0.33)

Extensions:
dev-spaces-preview (0.1.6)
mesh (0.9.3)

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Users\mapoitra\.azure\cliextensions'

Python (Windows) 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)]

**Comment by YuzorMa** [comment]
@mapoitras Are you still facing installation issues with the latest Azure CLI version?
