### ISSUE TITLE
Setup failing with 'Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.'

### ISSUE THREAD

**Issue by cnsgithub** [Azure/dev-spaces#72]
Hi,

I am following the [Quickstart: Create a Kubernetes dev space with Azure Dev Spaces (Java and VS Code)](https://docs.microsoft.com/en-us/azure/dev-spaces/quickstart-java) guide.

The listed prerequisites are met.

**Environment:**

- AKS cluster with Dev Spaces enabled: `kubectl version`

````
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
````

- Azure CLI: `az --version`

````
azure-cli (2.0.57)
````

- Azure Dev Spaces CLI: `azds --version`

````
Azure Dev Spaces CLI (Preview)
0.1.20190320.5
API v2.17
````

**Error:**

When trying to set up Dev Spaces I get an unspecific error. Unfortunately, `--verbose` does not produce more output.

````
az aks use-dev-spaces --resource-group <resourceGroup> --name <clusterName>

Selecting Azure Dev Spaces Controller '<clusterName>' in resource group '<resourceGroup>' that targets resource '<clusterName>' in resource group '<resourceGroup>'...<1s

Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
````

The same happens in `azds` when executing from within the `webfrontend` folder contained in the quickstart example:

````
azds up

No dev space is currently selected. Use 'azds space select' to select a dev space.
````

````
azds space select

Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
````

Unfortunately, I cannot find any log files written to `%temp%` as suggested in https://github.com/Azure/dev-spaces/issues/25.

Any help would be appreciated.

**Comment by cnsgithub** [comment]
Ok, I tried the same commands with another resource group, namely the `MC_<resourceGroup>_westeurope_<clusterName` one.

This reveals a permission problem:

```
az aks use-dev-spaces --resource-group MC_<resourceGroup>_westeurope_<clusterName> --name clusterName

Selecting Azure Dev Spaces Controller 'cadenas' in resource group 'MC_CNS_westeurope_cadenas' that targets resource 'cadenas' in resource group 'CNS'...<1s

Failed to get Azure Dev Spaces Controller '<clusterName' in resource group 'MC_<resourceGroup>_westeurope_<clusterName>' in subscription '<subscription>'. The client '<userEmail>' with object id '<userId>' does not have authorization to perform action 'Microsoft.DevSpaces/controllers/read' over scope '/subscriptions/<subscription>/resourceGroups/MC_<resourceGroup>_westeurope_<clusterName>/providers/Microsoft.DevSpaces/controllers/<clusterName>'.
````

Which role has to be assigned? I am already owner of the `MC_<resourceGroup>_westeurope_<clusterName>` resource group.

Thanks.

**Comment by YuzorMa** [comment]
@cnsgithub Thanks for reporting this.  We're investigating the logs on our side and we'll let you know what we find.

In the meantime, it is odd that you don't see any logs in %Temp%.  Are you running on Windows?  Do you see an "Azure Dev Spaces" folder in your %temp% directory and there are no files in it, or do you not even see the folder?

**Comment by cnsgithub** [comment]
> In the meantime, it is odd that you don't see any logs in %Temp%. Are you running on Windows? Do you see an "Azure Dev Spaces" folder in your %temp% directory and there are no files in it, or do you not even see the folder?

Sorry about that, now I've found the `Azure Dev Spaces` folder in `%temp%`. It was a bit misleading, because there have been two `%temp%\Azure*_azds*.log` files before with older modification dates so I expected the new ones to be directly in `%temp%` as well.

This is what I've found in `%temp%\Azure Dev Spaces\azds-cli*.txt` for the non-`MC_` resource group:

````
"2019-03-26T05:09:03.1601581Z" : ERROR: Logging handled exception: Microsoft.Azure.DevSpaces.Client.Exceptions.OperationIdException: {"RequestId":null,"ClientRequestId":null,"CorrelationRequestId":null,"Format":"The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.","Args":[],"Message":"The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.","Data":{},"InnerException":{"ClassName":"System.InvalidOperationException","Message":"The character set provided in ContentType is invalid. Cannot read content as string using an invalid character set.","Data":null,"InnerException":{"ClassName":"System.ArgumentException","Message":"'\"UTF-8\"' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Text.EncodingTable.internalGetCodePageFromName(String name)
   at System.Text.EncodingTable.GetCodePageFromName(String name)
   at System.Text.Encoding.GetEncoding(String name)
   at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147024809,"Source":"System.Private.CoreLib","WatsonBuckets":null,"ParamName":"name"},"HelpURL":null,"StackTraceString":"   at System.Net.Http.HttpContent.ReadBufferAsString(ArraySegment`1 buffer, HttpContentHeaders headers)
   at System.Net.Http.HttpContent.ReadBufferedContentAsString()
   at System.Net.Http.HttpContent.<>c.<ReadAsStringAsync>b__36_0(HttpContent s)
   at System.Net.Http.HttpContent.WaitAndReturnAsync[TState,TResult](Task waitTask, TState state, Func`2 returnFunc)
   at Microsoft.Azure.DevSpaces.ExecService.Client.SpacesOperations.ListSpacesWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken) in E:\\A\\_work\\1386\\s\\src\\execsvc.client.autogen\\SpacesOperations.cs:line 624
   at Microsoft.Azure.DevSpaces.Client.ManagementClients.SpaceManagementClientImplementation.ListSpacesAsync(CancellationToken cancellationToken) in E:\\A\\_work\\1386\\s\\src\\client\\Client\\ManagementClients\\SpaceManagementClientImplementation.cs:line 246
   at Microsoft.Azure.DevSpaces.Client.Extensions.OwnedExtensions.<>c__DisplayClass2_0`2.<<TryRunOwnedOperationThenDisposeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.DevSpaces.Client.Utilities.AutofacUtilities.TryRunWithErrorPropagationAsync[T](Func`1 func, ILog log, IOperationContext operationContext)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233079,"Source":"System.Net.Http","WatsonBuckets":null},"TargetSite":null,"StackTrace":"   at Microsoft.Azure.DevSpaces.Client.Utilities.AutofacUtilities.TryRunWithErrorPropagationAsync[T](Func`1 func, ILog log, IOperationContext operationContext) in E:\\A\\_work\\1386\\s\\src\\client\\Utilities\\AutofacUtilities.cs:line 118
   at Microsoft.Azure.DevSpaces.Cli.Commands.Space.SpaceCommandBase.GetSpaceList() in E:\\A\\_work\\1386\\s\\src\\cli\\Commands\\Space\\SpaceCommandBase.cs:line 50
   at Microsoft.Azure.DevSpaces.Cli.Commands.Space.SpaceSelectCommand.ExecuteAsync() in E:\\A\\_work\\1386\\s\\src\\cli\\Commands\\Space\\SpaceSelectCommand.cs:line 85
   at Microsoft.Azure.DevSpaces.Cli.Commands.Controller.UseDevSpacesCommand.ExecuteAsync() in E:\\A\\_work\\1386\\s\\src\\cli\\Commands\\Controller\\UseDevSpacesCommand.cs:line 146
   at Microsoft.Azure.DevSpaces.Cli.DevSpacesCliApp.RunCommandAsync(String[] args, CancellationToken cancellationToken) in E:\\A\\_work\\1386\\s\\src\\cli\\DevSpacesCliApp.cs:line 235
   at Microsoft.Azure.DevSpaces.Cli.DevSpacesCliApp.ExecuteAsync(String[] args) in E:\\A\\_work\\1386\\s\\src\\cli\\DevSpacesCliApp.cs:line 138","HelpLink":null,"Source":null,"HResult":-2146233088}(version=0.1.20190320.5)(apiVersion=2.17)(subscriptionId=<subscription>)(CommandId=9eece028-7d56-44e7-a19c-b08559107fe0)(ProcessId=13960)
````

I just wonder what `E:\\A\\_work\\1386\\s\\src\\cli\\Commands\\Controller` in the stack trace means? There is no `E:` drive on my workstation.  Is it at the remote machine running the Dev Spaces controller?

I also wonder which resource group is the correct one to use for `az aks use-dev-spaces`. The one the AKS cluster resides in or the `MC_` one created automatically by AKS?

**Comment by YuzorMa** [comment]
@cnsgithub A couple points here so I'll try to hit them all:

- We used to drop our log files directly in the %Temp% folder but now we put them in a sub-directory so we don't pollute (you must be a long-time user :-))
-The "E:\\A\\..." is an artifact of the build process of the CLI
-You should use the resource group that contains the AKS cluster, not the one that contains the infrastructure
- The call stack you pasted matched what we found in our telemetry.  We're investigating and will keep you posted as soon as we find the cause and/or a workaround

In the meantime, can you try the following which breaks down the "use" command into its parts:
1. Run "azds controller list" to see if you have a controller (your failure looks like it happened after the controller was created)
2. If you have one, select it ("azds controller select"
3. Run "azds space list" to see if you have any spaces
4. Run "azds space create" to create a space

If all of this works, then you should be unblocked.  If not, let me know where it fails and we'll investigate further.

**Comment by eiximenis** [comment]
Hi!
Same happened to me. I had a controller created and use --update option of "az aks use-dev-spaces" for udating the CLI.
CLI was updated and then I received the error.

```
λ  az aks use-dev-spaces -n tailwindtradersaksmrucyedjn3p5m -g tt-devspaces --update
Installing Dev Spaces (Preview) commands...
A separate window will open to guide you through the installation process.
Selecting Azure Dev Spaces Controller 'tailwindtradersaksmrucyedjn3p5m' in resource group 'tt-devspaces' that targets resource 'tailwindtradersaksmrucyedjn3p5m' in resource group 'tt-devspaces'...2s

Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
``` 

I found this in my logs folder:

```
"2019-03-26T17:13:19.2771237Z" : {"eventName":"DevSpacesManagementClient-EnsureResourceProviderRegistration","properties":{"resourceProviderNamespace":"Microsoft.DevSpaces","result":"Succeeded"},"metrics":{"duration":1043.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=38c0cf6b-77ea-499a-83df-22899430516b)(correlationRequestId=d8f042eb-e8b7-452a-ab73-b8060c53474e)(requestId=d8f042eb-e8b7-452a-ab73-b8060c53474e)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=7cc87a53-0672-47a2-a7df-6e907d13c952)
"2019-03-26T17:13:20.6467352Z" : {"eventName":"DevSpacesManagementClient-ListInSubscription","properties":{"result":"Succeeded"},"metrics":{"duration":2459.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=ad8f45d3-c168-4d49-84df-2562ba980eab)(correlationRequestId=1d0afd45-6f8c-4f06-80e7-02b45259c4b6)(requestId=cc48a29e-7b03-403d-a86a-39cac4f5e694)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=7cc87a53-0672-47a2-a7df-6e907d13c952)
"2019-03-26T17:13:21.2699185Z" : {"eventName":"DevSpacesManagementClient-EnsureResourceProviderRegistration","properties":{"resourceProviderNamespace":"Microsoft.DevSpaces","result":"Succeeded"},"metrics":{"duration":584.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=8c093bb6-4e17-4ab4-b269-80dd1b5b5edc)(correlationRequestId=4e35311d-edc6-4960-97ac-6d013b349660)(requestId=4e35311d-edc6-4960-97ac-6d013b349660)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=541ee268-4066-487a-9bce-c3099e9be868)
"2019-03-26T17:13:21.4174529Z" : {"eventName":"DevSpacesManagementClient-EnsureResourceProviderRegistration","properties":{"resourceProviderNamespace":"Microsoft.DevSpaces","result":"Succeeded"},"metrics":{"duration":136.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=554e1adb-e711-409e-bd6f-ba150a886501)(correlationRequestId=76ee7a49-f200-4a4c-b698-8e601fdd7257)(requestId=76ee7a49-f200-4a4c-b698-8e601fdd7257)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=541ee268-4066-487a-9bce-c3099e9be868)
"2019-03-26T17:13:22.6878553Z" : {"eventName":"DevSpacesManagementClient-Get","properties":{"name":"tailwindtradersaksmrucyedjn3p5m","resourceGroupName":"tt-devspaces","result":"Succeeded"},"metrics":{"duration":1412.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=673fa2c5-39e4-4955-b714-0a5039a29c7c)(correlationRequestId=82da35fb-223b-4475-a64a-b7d36095c8fc)(requestId=53d41698-afa6-4c05-b551-757f30cadf03)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=541ee268-4066-487a-9bce-c3099e9be868)
"2019-03-26T17:13:23.0047321Z" : {"eventName":"DevSpacesManagementClient-ListConnectionDetails","properties":{"name":"tailwindtradersaksmrucyedjn3p5m","resourceGroupName":"tt-devspaces","result":"Succeeded"},"metrics":{"duration":2319.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=05259617-ffad-4cad-9c75-f79a5d1c6d3d)(correlationRequestId=a6b883ca-fcd0-4308-9855-6b8bc05316e6)(requestId=f3ec95a9-279d-4280-aa25-0830cb834ef8)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=541ee268-4066-487a-9bce-c3099e9be868)
"2019-03-26T17:13:23.0156812Z" : {"eventName":"DevSpacesManagementClient-Select","properties":{"name":"tailwindtradersaksmrucyedjn3p5m","resourceGroupName":"tt-devspaces","result":"Succeeded"},"metrics":{"duration":2339.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=05259617-ffad-4cad-9c75-f79a5d1c6d3d)(correlationRequestId=a6b883ca-fcd0-4308-9855-6b8bc05316e6)(requestId=f3ec95a9-279d-4280-aa25-0830cb834ef8)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=541ee268-4066-487a-9bce-c3099e9be868)
"2019-03-26T17:13:23.6352292Z" : {"eventName":"DevSpacesManagementClient-EnsureResourceProviderRegistration","properties":{"resourceProviderNamespace":"Microsoft.DevSpaces","result":"Succeeded"},"metrics":{"duration":575.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=3cc864cd-c1e0-4eb9-8ee1-225b432e0513)(correlationRequestId=f6bcb2e3-55e3-4c7f-862b-faaa40393f8d)(requestId=f6bcb2e3-55e3-4c7f-862b-faaa40393f8d)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=e30068e7-39a7-4be1-be29-c53576a7c81d)
"2019-03-26T17:13:23.7787377Z" : {"eventName":"DevSpacesManagementClient-EnsureResourceProviderRegistration","properties":{"resourceProviderNamespace":"Microsoft.DevSpaces","result":"Succeeded"},"metrics":{"duration":143.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=0e57cbb6-40ce-4467-b463-713915676b6d)(correlationRequestId=336b9f7a-4194-47bc-bc20-30dbdf7f4f17)(requestId=336b9f7a-4194-47bc-bc20-30dbdf7f4f17)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=e30068e7-39a7-4be1-be29-c53576a7c81d)
"2019-03-26T17:13:24.9805131Z" : {"eventName":"DevSpacesManagementClient-Get","properties":{"name":"tailwindtradersaksmrucyedjn3p5m","resourceGroupName":"tt-devspaces","result":"Succeeded"},"metrics":{"duration":1345.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=ac6f175b-8d41-428f-9522-e4115c9fe360)(correlationRequestId=12ee3529-2487-41d4-8553-5a6417a27150)(requestId=5ce4510e-ea56-4180-b6da-819aaa5897dc)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=e30068e7-39a7-4be1-be29-c53576a7c81d)
"2019-03-26T17:13:25.3314963Z" : {"eventName":"DevSpacesManagementClient-ListConnectionDetails","properties":{"name":"tailwindtradersaksmrucyedjn3p5m","resourceGroupName":"tt-devspaces","result":"Succeeded"},"metrics":{"duration":2271.0}}(version=0.1.20190320.5)(apiVersion=2.17)(clientRequestId=ab22e70c-ca1d-4a2a-9f00-fc939cb4b9ae)(correlationRequestId=89498eb5-0844-4d64-ae8a-792f883911e6)(requestId=8a070df3-30ef-47f7-9414-1131bc2844ed)(subscriptionId=acd68168-1cca-4202-83d5-16d8cad955e3)(ProcessId=281016)(ClientSdkOperationId=e30068e7-39a7-4be1-be29-c53576a7c81d)
"2019-03-26T17:14:26.1184214Z" : {"eventName":"SpacesServiceClient-List","properties":{"result":"Failed"},"metrics":{"duration":60035.0}}(version=0.1.20190320.5)(apiVersion=2.17)(ProcessId=281016)(ClientSdkOperationId=4d8902ff-bca3-4315-8014-eba07497a302)
"2019-03-26T17:14:26.3582711Z" : WARNING: Logging handled exception: System.Threading.Tasks.TaskCanceledException: {"ClassName":"System.Threading.Tasks.TaskCanceledException","Message":"The operation was canceled.","Data":null,"InnerException":{"ClassName":"System.IO.IOException","Message":"Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.","Data":null,"InnerException":{"ClassName":"System.Net.Sockets.SocketException","Message":"The I/O operation has been aborted because of either a thread exit or an application request","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":null,"RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467259,"Source":null,"WatsonBuckets":null,"NativeErrorCode":995},"HelpURL":null,"StackTraceString":"   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)\r\n   at System.Net.Security.SslStreamInternal.<FillBufferAsync>g__InternalFillBufferAsync|38_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)\r\n   at System.Net.Security.SslStreamInternal.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)\r\n   at System.Net.Http.HttpConnection.FillAsync()\r\n   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)\r\n   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146232800,"Source":"System.Net.Sockets","WatsonBuckets":null},"HelpURL":null,"StackTraceString":"   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n   at Microsoft.Azure.DevSpaces.Client.Client.ManagementClients.ApiVersionCheckerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in E:\\A\\_work\\1386\\s\\src\\client\\Client\\ManagementClients\\ApiVersionCheckerHttpHandler.cs:line 26\r\n   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)\r\n   at Microsoft.Azure.DevSpaces.ExecService.Client.SpacesOperations.ListSpacesWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken) in E:\\A\\_work\\1386\\s\\src\\execsvc.client.autogen\\SpacesOperations.cs:line 611\r\n   at Microsoft.Azure.DevSpaces.Client.ManagementClients.SpaceManagementClientImplementation.ListSpacesAsync(CancellationToken cancellationToken) in E:\\A\\_work\\1386\\s\\src\\client\\Client\\ManagementClients\\SpaceManagementClientImplementation.cs:line 246\r\n   at Microsoft.Azure.DevSpaces.Client.Extensions.OwnedExtensions.<>c__DisplayClass2_0`2.<<TryRunOwnedOperationThenDisposeAsync>b__0>d.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Microsoft.Azure.DevSpaces.Client.Utilities.AutofacUtilities.TryRunWithErrorPropagationAsync[T](Func`1 func, ILog log, IOperationContext operationContext)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233029,"Source":"Microsoft.Rest.ClientRuntime","WatsonBuckets":null}(version=0.1.20190320.5)(apiVersion=2.17)(ProcessId=281016)(ClientSdkOperationId=4d8902ff-bca3-4315-8014-eba07497a302)
```

Hope this helps!

**Comment by cnsgithub** [comment]
@YuzorMa Thanks for your clarifications so far.

> * Run "azds controller list" to see if you have a controller (your failure looks like it happened after the controller was created)

````
Azure Dev Spaces Controllers in subscription '<subscription>':
   Name     ResourceGroup  Location    ProvisioningState
-  -------  -------------  ----------  -----------------
*  <clusterName>  <resourceGroup>            westeurope  Succeeded
````

> * If you have one, select it ("azds controller select"

````
Azure Dev Spaces Controller '<clusterName>' in resource group '<resourceGroup>' in subscription '<subscription>' has been selected.
````

> * Run "azds space list" to see if you have any spaces

````
Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
````

> * Run "azds space create" to create a space

````
Specify --help for a list of available options and commands.
Unrecognized command or argument 'create'
````

**Comment by sanar-microsoft** [comment]
@cnsgithub We are still investigating this issue, can you provide the Fiddler trace(with response headers) by doing a GET on http://<dataplaneFqdn>/api/ping

You can get the dataplaneFqdn value from this file: C:\Users\<your user>\.azds\settings.json

**Comment by cnsgithub** [comment]
@sanar-microsoft Just tried the `dataplaneFqdn` from `%userprofile%\.azds\settings.json`. The DNS name in the form `azds-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.weu.azds.io` cannot be resolved. Also checked this from outside my network in CloudShell at Azure:
````
<user>@Azure:~$ nslookup
> azds-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.weu.azds.io
Server:         16x.63.129.xx
Address:        16x.63.129.xx#53

** server can't find azds-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx.weu.azds.io: NXDOMAIN
````
Weird?

**Comment by sanar-microsoft** [comment]
@cnsgithub I'm glad things are working for you and I agree the error message needs improvement, we will try to fix this in our next update. Sorry for all the trouble.

**Comment by hugginssd** [comment]
Also faced the same error "An unexpected client error has occured" on the On-Prem D365FO. Up to now I cant resolve it. An suggestion??
