### ISSUE TITLE
unsupported operand type(s) for |: 'DefaultStr' and 'bool'

### ISSUE THREAD

**Issue by awysza** [Azure/dev-spaces#9]
running 
C:\WINDOWS\system32>az aks use-dev-spaces -n aksa -g aksarg

and getting

unsupported operand type(s) for |: 'DefaultStr' and 'bool'
Traceback (most recent call last):
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\knack\knack\cli.py", line 197, in invoke
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\azure-cli-core\azure\cli\core\commands\__init__.py", line 336, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\six\six.py", line 693, in reraise
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\azure-cli-core\azure\cli\core\commands\__init__.py", line 310, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\azure-cli-core\azure\cli\core\commands\__init__.py", line 171, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\knack\knack\commands.py", line 109, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\azure-cli-core\azure\cli\core\__init__.py", line 420, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-4rn35c0b\azure-cli-acs\azure\cli\command_modules\acs\custom.py", line 1516, in aks_use_dev_spaces
  File "C:\Users\anskob\.azure\cliextensions\dev-spaces-preview\azext_dev_spaces_preview\custom.py", line 38, in ads_use_dev_spaces
    azds_cli = _install_dev_spaces_cli(update)
  File "C:\Users\anskob\.azure\cliextensions\dev-spaces-preview\azext_dev_spaces_preview\custom.py", line 118, in _install_dev_spaces_cli
    should_install_azds = force_install | (not _is_dev_spaces_installed(azds_cli))
TypeError: unsupported operand type(s) for |: 'DefaultStr' and 'bool'

**Comment by YuzorMa** [comment]
It looks like you may have an older version of the tools.  Can you verify that your azure cli version is at least 2.0.38 and your dev spaces extension is at least 0.1.6?  You can see the versions by running 'az --version'.

If they are older, you can get a newer Azure CLI from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest.  You can update the extension by running 'az extension update -n dev-spaces-preview'.
